### ISSUE TITLE
Add custom scalar types

### ISSUE THREAD

**Issue by tamizhvendan** [graphqlize/graphqlize#24]
- [x] Date
- [x] Time
- [x] Time With Time Zone
- [x] DateTime 
- [x] DateTime With Time Zone
- [x] Long
- [x] BigDecimal
- [x] BigInteger

**Comment by ieugen** [comment]
Nice, 

Some work regarding scalars in graphl-java, for reference:

https://github.com/graphql-java/graphql-java-extended-scalars
https://www.graphql-java.com/documentation/v14/scalars/
