### ISSUE TITLE
Enable Pagination in lists using limit and offset parameters

### ISSUE THREAD

**Issue by tamizhvendan** [graphqlize/graphqlize#8]

**Comment by ieugen** [comment]
These resources might help: 

https://use-the-index-luke.com/blog/2013-07/pagination-done-the-postgresql-way
Also see this discussion on pagination in graphql-java https://github.com/graphql-java/graphql-java/issues/794 . 

In our graphql application built with graphql-java and graphql-java-tools we implemented Relay style pagination with the help of window functions to maintain a stable cursor ID. 

We used to look ahead in the query and batched them for performance, reasons.
I think the implementation should care about whether it uses the data loader or not.

This has some implications when dealing with authorization and data access. In our code we used a tenant_id column for multi tenancy with PostgreSQL. 

Sample code we use to batch load some data from db for graphql-java with data loader and relay pagination:


```
  assessments(
    first: Int
    after: String
    last: Int
    before: String
    filter: AssessmentFilter
    sort: AssessmentSortSpecifier
  ): AssessmentConnection!

type AssessmentConnection {
    edges: [AssessmentEdge!]
    pageInfo: PageInfo!
    totalCount: Int!
    indexFrom: Int
    indexTo: Int
}

# Represents an edge to a single Assessment
type AssessmentEdge {
    # The assessment
    node: Assessment
    # The cursor for this assessment
    cursor: ConnectionCursor
}
scalar ConnectionCursor

```
Data access layer is done with Jooq so it should be readable SQL. It's also redacted and changed a bit to make it more readable. 
As I mentioned, we use window functions to generate a stable, unique cursor for each row in our query. 
For the same query parameters, the results are stable. 
Each elements gets its own cursor. 

We do some extra processing (not visible in the code bellow) when back navigation is required. We reverse the collection elements and stuff like that. I think it could be implemented in SQL. 

```
public LinkedHashMap<Long, ConnectionData<Long>> fetchAssessmentConnection(
      List<Long> accountIdz,
      AssessmentFilter filter,
      AssessmentSortSpecifier sortSpecifier,
      IntCursorPagination pagination) {

    // build query
    Condition whereCondition =
        ASSESSMENTS.ACCOUNT_ID.in(accountIdz);

    if (filter != null) {
      if (filter.getStatus() != null) {
        whereCondition = whereCondition.and(ASSESSMENTS.STATUS.eq(filter.getStatus()));
      }
      if (filter.getStartDate() != null) {
        LocalDate startDate = CommonHelper.localDateTimeFromString(filter.getStartDate()).get();
        whereCondition =
            whereCondition.and(ASSESSMENTS.LAST_UPDATETIME.ge(startDate.atStartOfDay()));
      }
      if (filter.getEndDate() != null) {
        LocalDate endDate = CommonHelper.localDateTimeFromString(filter.getEndDate()).get();
        whereCondition =
            whereCondition.and(ASSESSMENTS.LAST_UPDATETIME.le(DateTimeUtils.getEndOfDay(endDate)));
      }

    }

    SortOrder sortOrder = sortOrder(sortSpecifier.getSortDir());
    SortField sortField = sortSpecifier.getSortBy().getDbColumn().sort(sortOrder);

    SelectConditionStep<Record4<Long, Long, Integer, Integer>> nested =
        dsl.select(
                ASSESSMENTS.ACCOUNT_ID,
                ASSESSMENTS.ID,
                rank()
                    .over()
                    .partitionBy(ASSESSMENTS.ACCOUNT_ID)
                    .orderBy(sortField, ASSESSMENTS.ID.sort(sortOrder))
                    .as(cursorField),
                count().over().partitionBy(ASSESSMENTS.ACCOUNT_ID).as(totalField))
            .from(ASSESSMENTS)
            .innerJoin(RESPONDENTS)
            .on(ASSESSMENTS.RESPONDENT_ID.eq(RESPONDENTS.ID))
            .innerJoin(ASSMT_TEMPLATES)
            .on((ASSMT_TEMPLATES.ID.eq(ASSESSMENTS.ASSMT_TEMPLATE_ID)))
            .where(whereCondition);

    // execute query
    Result<Record> records =
        dsl.select(nested.fields()).from(nested).where(buildCursorCondition(pagination)).fetch();

    // group account id + totalRecords -> record
    LinkedHashMap<Long, List<Record>> rez =
        records.stream()
            .collect(
                groupingBy(
                    record -> record.get(ASSESSMENTS.ACCOUNT_ID),
                    () -> new LinkedHashMap<>(),
                    toList()));

    LinkedHashMap<Long, ConnectionData<Long>> accounts = new LinkedHashMap<>();
    for (Long accountId : accountIdz) {
      ConnectionData<Long> connection = new ConnectionData();
      accounts.put(accountId, connection);
      Integer totalRecords = null;
      if (rez.get(accountId) != null) {
        for (Record record : rez.get(accountId)) {
          Long templateId = record.get(ASSESSMENTS.ID);
          Integer cursor = record.get(cursorField);
          totalRecords = record.get(totalField);
          connection.getIds().add(templateId);
          connection.getCursors().add(new IntConnectionCursor(cursor));
        }
        connection.setTotalRecords(totalRecords);
      }
    }
    return accounts;
  }
```

**Comment by tamizhvendan** [comment]
Thanks, @ieugen for the detailed comment and the reference implementation. Is it possible to share a high-level implementation of the `buildCursorCondition` method implementation? I am curious to know to it transforms the `IntCursorPagination` to a `where` condition.

**Comment by tamizhvendan** [comment]
GraphQLize will be supporting pagination in three ways. 

1. Using Offset & Limit
2. [Using Relay Spec](https://github.com/graphqlize/graphqlize/issues/6)
3. Using row value via `where` filter.

To start with I am going to focus on 1 & 3 and then on 2 as relay spec implementation will take some time. 

The idea is to give an option like [Postgraphile](https://www.graphile.org/postgraphile/connections/#advice) and let the user choose what would work for them. 
/cc @ieugen

**Comment by tamizhvendan** [comment]
It's [Done](https://www.graphqlize.org/docs/queries/pagination/limit-and-offset/)
